package com.netflix.ice.processor.postproc;

import java.util.List;

import com.netflix.ice.processor.config.S3BucketConfig;
import com.netflix.ice.processor.postproc.RuleConfig.Aggregation;

/**
 * Post Processor Report Configuration
 * 
 * Specifies where to save reports generated by the post processor and the aggregation levels desired.
 * Aggregation levels can include one or more of the values: monthly, daily, hourly
 * 
 * If includeCostType is set to true, then an additional costType column is added to the report.
 *
 */
public class ReportConfig {
	public enum DataType {
		cost,
		usage;
	}
	
	private S3BucketConfig s3Bucket;
	private List<Aggregation> aggregate;
	private List<DataType> types;

	public S3BucketConfig getS3Bucket() {
		return s3Bucket;
	}
	public void setS3Bucket(S3BucketConfig s3Bucket) {
		this.s3Bucket = s3Bucket;
	}
	public List<Aggregation> getAggregate() {
		return aggregate;
	}
	public void setAggregate(List<Aggregation> aggregate) {
		this.aggregate = aggregate;
	}
	public List<DataType> getTypes() {
		return types;
	}
	public void setTypes(List<DataType> types) {
		this.types = types;
	}

}
